class Book {
  String name;
  String type;
  String publisher;
  DateTime date;
  String imgUrl;
  num score;
  num ratings;
  String review;
  num height;
  Book(
    this.name,
    this.type,
    this.publisher,
    this.date,
    this.imgUrl,
    this.score,
    this.ratings,
    this.review,
    this.height,
  );
  static List<Book> generateBooks() {
    return [
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/one.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/two.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/three.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/four.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/five.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/six.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/one.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/two.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/three.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/four.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/five.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/six.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/one.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/two.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/three.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/four.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/five.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0),
      Book(
          "The obstacle is the way",
          "Self help",
          "Ryan holiday",
          DateTime(2019, 3, 23),
          "assets/images/six.jpg",
          4.7,
          892,
          "Quite amazing book jdbvshbd bbhbshb sb",
          220.0)
    ];
  }
}
